"""Add reassignments_count to Participant model

Revision ID: 093c950f761e
Revises: 
Create Date: 2025-03-27 00:43:58.672685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093c950f761e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('reassignments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'reassignments_count')
    # ### end Alembic commands ###
