"""empty message

Revision ID: 741b2aaae3c5
Revises: 
Create Date: 2025-08-16 19:24:11.568536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741b2aaae3c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('emergency_contact', sa.String(length=100), nullable=True))
    op.add_column('participant', sa.Column('emergency_phone', sa.String(length=20), nullable=True))
    op.add_column('participant', sa.Column('special_requirements', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('session_assignment_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'session_assignment_notes')
    op.drop_column('participant', 'special_requirements')
    op.drop_column('participant', 'emergency_phone')
    op.drop_column('participant', 'emergency_contact')
    # ### end Alembic commands ###
