"""empty message

Revision ID: 74b5ad17a4b7
Revises: 
Create Date: 2025-08-21 02:20:36.970200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b5ad17a4b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'profile_photo_path')
    # ### end Alembic commands ###
